<a href="https://colab.research.google.com/github/Atul-Kashyap/Tensorflow2.X/blob/master/TensorflowBeginnersModules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term
2.2.0


In [ ]:
hello = tf.constant("Hello")

In [ ]:
world = tf.constant("World")

In [ ]:
# hello is tensor object
type(hello)

tensorflow.python.framework.ops.Tensor

In [ ]:
print(hello)
# hello is a constant and tensor object of string data type

Tensor("Const_1:0", shape=(), dtype=string)


In [ ]:
# create a tensorflow session 
with tf.Session() as sess:
  result = sess.run(hello+world)


In [ ]:
print(result)
# b represents bytes literals

b'HelloWorld'


In [ ]:
a = tf.constant(10)
b = tf.constant(20)

In [ ]:
type(a)

tensorflow.python.framework.ops.Tensor

In [ ]:
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [ ]:
a + b

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [ ]:
print(a+b)

Tensor("add_7:0", shape=(), dtype=int32)


In [ ]:
with tf.Session() as sess:
  result = sess.run(a+b)

In [ ]:
print(result)

30


In [ ]:
const = tf.constant(10)


In [ ]:
fill_mat = tf.fill((4,4),10)

In [ ]:
myzero = tf.zeros((4,4))

In [ ]:
myone = tf.ones((4,4))

In [ ]:
myrandn = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [ ]:
myrandu = tf.random_uniform((4,4),minval = 0, maxval = 10000)

In [ ]:
myzero

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [ ]:
my_ops = [const,myzero,myone,myrandn, myrandu, myzero]

In [ ]:
sess = tf.InteractiveSession()

In [ ]:
for op in my_ops:
  print(sess.run(op))
  print("\n")


10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.07448637 -1.042367   -0.03045169  0.15863459]
 [ 0.68213373 -1.6318685  -0.7973686  -0.14394327]
 [-1.5833719  -3.1363251   0.9187874   1.6929916 ]
 [-0.9358721  -0.40393215 -0.2658305  -2.508821  ]]


[[3370.3684 9268.198  8444.548  3817.661 ]
 [4583.205  1245.0874 4499.0825 1858.2273]
 [1497.3319 8176.782  5944.872  3565.8252]
 [6781.2515 9346.455  8450.924  5796.1655]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]




In [ ]:
a = tf.constant([ [1,2],
                 [3,4] ])


In [ ]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [ ]:
b = tf.constant([ [10], [100] ])

In [ ]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [ ]:
result = tf.matmul(a,b)

In [ ]:
with tf.Session() as sess:
  print(sess.run(result))

[[210]
 [430]]


In [ ]:
result.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [ ]:
result.eval()

array([[210],
       [430]], dtype=int32)

Tensorflow Graph

In [ ]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [ ]:
with tf.Session() as sess:
  result = sess.run(n3)

In [ ]:
print(result)

3


In [ ]:
print(n3)

Tensor("add_9:0", shape=(), dtype=int32)


In [ ]:
print(tf.get_default_graph())

In [ ]:
g = tf.Graph()

In [ ]:
print(g)

In [ ]:
graph_one = tf.get_default_graph()

In [ ]:
print(graph_one)

In [ ]:
graph_two = tf.Graph()

In [ ]:
print(graph_two)

In [ ]:
# there are two graph object graph_one and graph_two 
# graph_two is now default graph
with graph_two.as_default():
  print(graph_two is tf.get_default_graph())

True


In [ ]:
#  but here graph_two is not a default graph
print(graph_two is tf.get_default_graph())

False


In [ ]:
here graph_one is default graph
print(graph_one is tf.get_default_graph())

True


# **Variables and Placeholders**

There are two types of tensor objects in a graph:
 

1.   Variables
2.   Placeholders



Note: 
* During the optimization process, Tensorflow tunes the parameters of the model 
* Variables can hold the values of weights and biases throughout the session.
Variables need to be initialized.


* Placeholders are initially empty and are used to feed in the actual training examples.
* However they do need a declared expected data type (tf.float32) with an optional shape argument.





In [ ]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [ ]:
my_tensor = tf.random_uniform((4,4),0, 1)

In [ ]:
print(my_tensor)

Tensor("random_uniform_3/RandomUniform:0", shape=(4, 4), dtype=float32)


In [ ]:
my_var = tf.Variable(initial_value = my_tensor)

In [ ]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [ ]:
#if you try to run the session then it shows error because you need to initialize thr global variables
#sess.run(my_var)

In [ ]:
init = tf.global_variables_initializer()

In [ ]:
sess.run(init)

In [ ]:
sess.run(my_var)

array([[0.8909323 , 0.32109165, 0.09439862, 0.44643867],
       [0.7875365 , 0.50206137, 0.25335002, 0.95415175],
       [0.4595939 , 0.5315008 , 0.11069953, 0.67650855],
       [0.08320606, 0.19642305, 0.0992415 , 0.99891937]], dtype=float32)

In [ ]:
ph = tf.placeholder(tf.float32, shape=(None,5))